jobs:
- job: build_upload
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    - group: GithubToken
    
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
  - script: |
      ls -al
      ./deploy.sh
    env:
      GITHUB_TOKEN: '$(Github_PagePushToken)'
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'Build'
